server:
  port: 8080
  servlet:
    context-path: /auction
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/auction_koi"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
file:
  base-dir: "${user.dir}\\-Ph-n-m-m-u-gi-c-Koi-cho-c-c-trang-tr-i\\frontend\\public\\img"

